require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Rails/PluckId:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
