name: brakeman

on:
  - push
  - pull_request

jobs:
  brakeman:
    runs-on: ubuntu-latest
    env:
      BUNDLE_CLEAN: 'true'
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      RAILS_ENV: test
      TZ: 'Asia/Tokyo'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run Brakeman
        run: bundle exec brakeman
